name: "Nueva funcionalidad"

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v3.5.3
      - name: Configurar Entorno Node.js 18.X
        uses: actions/setup-node@v2.5.2
        with:
            cache: "npm"
            node-version: "18"
      - name: Instalar Dependencias
        run: npm ci
      - name: Lint
        run: npm run lint
  
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v3.5.3
        with:
            fetch-dept: 0
      - name: Configurar Entorno Node.js 18.X
        uses: actions/setup-node@v2.5.2
        with:
            cache: "npm"
            node-version: "18"
      - name: Instalar Dependencias
        run: npm ci
      - name: Testing
        run: echo "Todas las pruebas superadas"